config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :products do
    resources :auctions, only: [ :create ] do
      resources :bids, only: [ :create ]
    end
    member do
      put :transfer
    end
  end

  root 'products#index'

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  belongs_to :product
  has_many :bids

  def top_bid
    bids.order(value: :desc).first
  end

  def current_bid
    top_bid.nil? ? value : top_bid.value
  end

  def ended?
    Time.now > ends_at
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :auction
  validates_numericality_of :value
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_one :auction

  def has_auction?
    auction.present?
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  def create
    product = Product.find(params[:product_id])
    auction = Auction.new(auction_params.merge! product_id: product.id)

    if auction.save
      redirect_to product, notice: "Product was set to auction."
    else
      redirect_to product, alert: "Something went wrong, please review your data."
    end
  end

  def auction_params
    params.require(:auction).permit(:value, :ends_at)
  end
end

app/controllers/bids_controller.rb
require 'place_bid'
class BidsController < ApplicationController

  def create
    service = PlaceBid.new(bid_params)
    if service.execute
      redirect_to product_path(params[:product_id]), notice: "Bid successfully placed."
    else
      redirect_to product_path(params[:product_id]), alert: "Something went wrong."
    end
  end


  private

  def bid_params
    params.require(:bid).permit(:value).merge!(user_id: current_user.id, auction_id: params[:auction_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json

  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params.merge! user_id: current_user.id)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def transfer
    product = Product.find(params[:id])
    if product.auction.ended?
      product.update_attribute(:user_id, product.auction.top_bid.user_id)
      redirect_to product, notice: "Successfully transfered the product."
    else
      redirect_to product, alert: "The auction hasn't ended yet."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Bunch 'o' Stuff", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Products", products_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <p class="navbar-text">
            You are signed in as <%= current_user.email %>. | |
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          </p>
        <% else %>
          <li>
            <%= link_to "Sign in", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/auctions/_status.html.erb
<% if @product.auction.top_bid.user_id == current_user.id %>
  <p>You won the auction!</p>
  <p>
    <%= link_to "Claim this product", transfer_product_path(@product), class: "btn btn-primary", method: :put %>
  </p>
<% else %>
  <p>You lost the auction.</p>
<% end %>

app/views/auctions/create.html.erb
<h1>Auctions#create</h1>
<p>Find me in app/views/auctions/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bunchostuff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'nav' %>

  <div class="container">
    <%= content_tag :div, alert , class: "flash bg-danger" if alert %>
    <%= content_tag :div, notice , class: "flash bg-success" if notice %>
    <%= yield %>
  </div>


</body>
</html>

app/views/products/_auction.html.erb
<% unless @product.has_auction? %>
  <h2>Put this product to auction</h2>
  <%= form_for [ @product, Auction.new ] do |f| %>
    <p>
      <%= f.text_field :value %>
    </p>
    <p>
      <%= f.datetime_select :ends_at %>
      <%= f.button class: "btn btn-primary" %>
    </p>
  <% end %>
<% end %>

app/views/products/_bid.html.erb
<% if @product.has_auction? %>
  <% if @product.auction.ended? %>
    <%= render "auctions/status" %>
  <% else %>
    <%= form_for [ @product, @product.auction, Bid.new ] do |f| %>
      <p class="message">
        <strong>
        <% if @product.auction.top_bid.present? %>
          <% if @product.auction.top_bid.user_id == current_user.id %>
            Current bid:
          <% else %>
            You were outbid:
          <% end %>
        <% else %>
          Current bid:
        <% end %>
        <%= @product.auction.current_bid %>
        </strong>
      </p>
      <p>
        Ends at:
        <%= l(@product.auction.ends_at, format: :long)%>
      </p>
      <p>
        <%= f.text_field :value %>
        <%= f.button class: "btn btn-primary" %>
      </p>
    <% end %>
  <% end %>
<% end %>


<script>
  <% if @product.has_auction? %>
    $(function() {
      var user_id = <%= current_user.id %>;
      var auction_id = <%= @product.auction.id %>;
      var form = $("#new_bid");

      var auctionSocket = new AuctionSocket(
        user_id,
        auction_id,
        form
      );
    });
  <% end %>
</script>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.image %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <%= image_tag @product.image, height: 200 %>
</p>
<br/>
<%= render 'auction' %>
<%= render 'bid' %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

<script>

  App = {
    websocket_url: "ws://<%= request.host %>:<%= request.port %>/"
  };

</script>